version: '3.4'
# RUNS BOTH THE BACKEND AND FRONTEND SERVICES PLEASE PLACE IT IN THE ROOT OF THE PROJECT where both the frontend and backend folders are located e.g. ai-rag-chatbot/frontend and ai-rag-chatbot/backend, so compose would be in ai-rag-chatbot/compose.yml
services:

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - './ai-rag-chatbot-frontend/compose/aws.env'

    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  ################################################################################
  # Frontend Service
  ################################################################################

  frontend-service:
    build: ./ai-rag-chatbot-frontend
    ports:
      - '3000:3000'
    links:
      - 'localstack:localstack'
      - 'redis:redis'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - './ai-rag-chatbot-frontend/compose/aws.env'

    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      LOCALSTACK_ENDPOINT: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - cdp-tenant


  ################################################################################
  # Backend Service
  ################################################################################
  backend-service:
    build:
      context: ./ai-rag-chatbot-backend
    ports:
      - '8085:8085'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - './ai-rag-chatbot-backend/compose/aws.env'
      - './ai-rag-chatbot-backend/compose/secrets.env'
    environment:
      PORT: 8085
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - README.md
            - "**/*.md"
            - "**/test_*.py"
            - tests/**/*
            - .git/**/*
            - .venv/**/*
            - .pytest_cache/**/*
            - .ruff_cache/**/*
            - .vscode/**/*
            - .github/**/*
            - requirements-dev.txt
            - pytest.ini
            - .pre-commit-config.yaml
            - sonar-project.properties
            - LICENCE
    networks:
      - cdp-tenant
################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
